# Generated by Django 5.1 on 2024-08-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_orderitems_order_alter_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
