# Generated by Django 5.1 on 2024-09-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
